// AUTO-GENERATED by scripts/generate-panoramas.mjs — do not edit by hand.
// Source of truth is the filenames in public/panoramas/ (YEAR_LAT_LNG_slug.jpg).
import type { HistoricalLocation } from "./locations";

export const panoramaLocations: HistoricalLocation[] = [
  {
    "id": "pano-1",
    "title": "Qin Dynasty Great Wall Construction",
    "year": -221,
    "lat": 40.3573,
    "lng": 115.9919,
    "imageUrl": "/panoramas/-221_40.3573_115.9919_qin-dynasty-great-wall-construction.jpg",
    "is360": true,
    "description": "Qin Dynasty Great Wall Construction — panoramă istorică de 360°, surprinsă în 221 î.Hr., în apropierea coordonatelor 40.3573, 115.9919.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 3-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-2",
    "title": "Construction Of The Great Pyramid Of Giza",
    "year": -2560,
    "lat": 29.9792,
    "lng": 31.1342,
    "imageUrl": "/panoramas/-2560_29.9792_31.1342_construction-of-the-great-pyramid-of-giza.jpg",
    "is360": true,
    "description": "Construction Of The Great Pyramid Of Giza — panoramă istorică de 360°, surprinsă în 2560 î.Hr., în apropierea coordonatelor 29.9792, 31.1342.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 26-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-3",
    "title": "Assassination Of Cleopatra Vii And Mark Antony",
    "year": -30,
    "lat": 31.2001,
    "lng": 29.9187,
    "imageUrl": "/panoramas/-30_31.2001_29.9187_assassination-of-cleopatra-vii-and-mark-antony.jpg",
    "is360": true,
    "description": "Assassination Of Cleopatra Vii And Mark Antony — panoramă istorică de 360°, surprinsă în 30 î.Hr., în apropierea coordonatelor 31.2001, 29.9187.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-4",
    "title": "Battle Of Actium",
    "year": -31,
    "lat": 38.9325,
    "lng": 20.7325,
    "imageUrl": "/panoramas/-31_38.9325_20.7325_battle-of-actium.jpg",
    "is360": true,
    "description": "Battle Of Actium — panoramă istorică de 360°, surprinsă în 31 î.Hr., în apropierea coordonatelor 38.9325, 20.7325.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-5",
    "title": "Battle Of Thermopylae",
    "year": -480,
    "lat": 38.7997,
    "lng": 22.5627,
    "imageUrl": "/panoramas/-480_38.7997_22.5627_battle-of-thermopylae.jpg",
    "is360": true,
    "description": "Battle Of Thermopylae — panoramă istorică de 360°, surprinsă în 480 î.Hr., în apropierea coordonatelor 38.7997, 22.5627.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 5-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-6",
    "title": "Burning Of The Library Of Alexandria",
    "year": -48,
    "lat": 31.1945,
    "lng": 29.8973,
    "imageUrl": "/panoramas/-48_31.1945_29.8973_burning-of-the-library-of-alexandria.jpg",
    "is360": true,
    "description": "Burning Of The Library Of Alexandria — panoramă istorică de 360°, surprinsă în 48 î.Hr., în apropierea coordonatelor 31.1945, 29.8973.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-7",
    "title": "Buddha's Enlightenment",
    "year": -528,
    "lat": 24.6957,
    "lng": 84.9912,
    "imageUrl": "/panoramas/-528_24.6957_84.9912_buddha-s-enlightenment.jpg",
    "is360": true,
    "description": "Buddha's Enlightenment — panoramă istorică de 360°, surprinsă în 528 î.Hr., în apropierea coordonatelor 24.6957, 84.9912.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 6-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-8",
    "title": "Founding Of Rome",
    "year": -753,
    "lat": 41.8902,
    "lng": 12.4845,
    "imageUrl": "/panoramas/-753_41.8902_12.4845_founding-of-rome.jpg",
    "is360": true,
    "description": "Founding Of Rome — panoramă istorică de 360°, surprinsă în 753 î.Hr., în apropierea coordonatelor 41.8902, 12.4845.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 8-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-9",
    "title": "Founding Of Carthage",
    "year": -814,
    "lat": 36.8529,
    "lng": 10.3341,
    "imageUrl": "/panoramas/-814_36.8529_10.3341_founding-of-carthage.jpg",
    "is360": true,
    "description": "Founding Of Carthage — panoramă istorică de 360°, surprinsă în 814 î.Hr., în apropierea coordonatelor 36.8529, 10.3341.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 9-lea î.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-10",
    "title": "Founding Of Teotihuacan",
    "year": 100,
    "lat": 19.692,
    "lng": -98.8436,
    "imageUrl": "/panoramas/100_19.6920_-98.8436_founding-of-teotihuacan.jpg",
    "is360": true,
    "description": "Founding Of Teotihuacan — panoramă istorică de 360°, surprinsă în anul 100, în apropierea coordonatelor 19.6920, -98.8436.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-11",
    "title": "Battle Of Hastings",
    "year": 1066,
    "lat": 50.9142,
    "lng": 0.4856,
    "imageUrl": "/panoramas/1066_50.9142_0.4856_battle-of-hastings.jpg",
    "is360": true,
    "description": "Battle Of Hastings — panoramă istorică de 360°, surprinsă în anul 1066, în apropierea coordonatelor 50.9142, 0.4856.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 11-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-12",
    "title": "Crowning Of William The Conqueror",
    "year": 1066,
    "lat": 51.4994,
    "lng": -0.1272,
    "imageUrl": "/panoramas/1066_51.4994_-0.1272_crowning-of-william-the-conqueror.jpg",
    "is360": true,
    "description": "Crowning Of William The Conqueror — panoramă istorică de 360°, surprinsă în anul 1066, în apropierea coordonatelor 51.4994, -0.1272.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 11-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-13",
    "title": "First Crusade Preaching",
    "year": 1095,
    "lat": 45.7766,
    "lng": 3.0874,
    "imageUrl": "/panoramas/1095_45.7766_3.0874_first-crusade-preaching.jpg",
    "is360": true,
    "description": "First Crusade Preaching — panoramă istorică de 360°, surprinsă în anul 1095, în apropierea coordonatelor 45.7766, 3.0874.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 11-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-14",
    "title": "Signing Of Magna Carta",
    "year": 1215,
    "lat": 51.4422,
    "lng": -0.5694,
    "imageUrl": "/panoramas/1215_51.4422_-0.5694_signing-of-magna-carta.jpg",
    "is360": true,
    "description": "Signing Of Magna Carta — panoramă istorică de 360°, surprinsă în anul 1215, în apropierea coordonatelor 51.4422, -0.5694.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 13-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-15",
    "title": "Genghis Khan's Death",
    "year": 1227,
    "lat": 38.4682,
    "lng": 106.2731,
    "imageUrl": "/panoramas/1227_38.4682_106.2731_genghis-khan-s-death.jpg",
    "is360": true,
    "description": "Genghis Khan's Death — panoramă istorică de 360°, surprinsă în anul 1227, în apropierea coordonatelor 38.4682, 106.2731.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 13-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-16",
    "title": "Sundiata Keita's Coronation Founding Of Mali Empire",
    "year": 1235,
    "lat": 11.2,
    "lng": -9.61,
    "imageUrl": "/panoramas/1235_11.2000_-9.6100_sundiata-keita-s-coronation-founding-of-mali-empire.jpg",
    "is360": true,
    "description": "Sundiata Keita's Coronation Founding Of Mali Empire — panoramă istorică de 360°, surprinsă în anul 1235, în apropierea coordonatelor 11.2000, -9.6100.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 13-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-17",
    "title": "Marco Polo's Arrival In Xanadu",
    "year": 1275,
    "lat": 42.355,
    "lng": 116.175,
    "imageUrl": "/panoramas/1275_42.3550_116.1750_marco-polo-s-arrival-in-xanadu.jpg",
    "is360": true,
    "description": "Marco Polo's Arrival In Xanadu — panoramă istorică de 360°, surprinsă în anul 1275, în apropierea coordonatelor 42.3550, 116.1750.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 13-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-18",
    "title": "Black Death In Florence",
    "year": 1348,
    "lat": 43.7695,
    "lng": 11.2558,
    "imageUrl": "/panoramas/1348_43.7695_11.2558_black-death-in-florence.jpg",
    "is360": true,
    "description": "Black Death In Florence — panoramă istorică de 360°, surprinsă în anul 1348, în apropierea coordonatelor 43.7695, 11.2558.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 14-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-19",
    "title": "Joan Of Arc's Trial And Execution",
    "year": 1431,
    "lat": 49.4429,
    "lng": 1.0911,
    "imageUrl": "/panoramas/1431_49.4429_1.0911_joan-of-arc-s-trial-and-execution.jpg",
    "is360": true,
    "description": "Joan Of Arc's Trial And Execution — panoramă istorică de 360°, surprinsă în anul 1431, în apropierea coordonatelor 49.4429, 1.0911.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-20",
    "title": "Gutenberg's Printing Press",
    "year": 1450,
    "lat": 50.0007,
    "lng": 8.2713,
    "imageUrl": "/panoramas/1450_50.0007_8.2713_gutenberg-s-printing-press.jpg",
    "is360": true,
    "description": "Gutenberg's Printing Press — panoramă istorică de 360°, surprinsă în anul 1450, în apropierea coordonatelor 50.0007, 8.2713.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-21",
    "title": "Fall Of Constantinople",
    "year": 1453,
    "lat": 41.018,
    "lng": 28.932,
    "imageUrl": "/panoramas/1453_41.0180_28.9320_fall-of-constantinople.jpg",
    "is360": true,
    "description": "Fall Of Constantinople — panoramă istorică de 360°, surprinsă în anul 1453, în apropierea coordonatelor 41.0180, 28.9320.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-22",
    "title": "Siege Of Constantinople",
    "year": 1453,
    "lat": 41.02,
    "lng": 28.9325,
    "imageUrl": "/panoramas/1453_41.0200_28.9325_siege-of-constantinople.jpg",
    "is360": true,
    "description": "Siege Of Constantinople — panoramă istorică de 360°, surprinsă în anul 1453, în apropierea coordonatelor 41.0200, 28.9325.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-23",
    "title": "Columbus First Landing",
    "year": 1492,
    "lat": 24.0625,
    "lng": -74.4795,
    "imageUrl": "/panoramas/1492_24.0625_-74.4795_columbus-first-landing.jpg",
    "is360": true,
    "description": "Columbus First Landing — panoramă istorică de 360°, surprinsă în anul 1492, în apropierea coordonatelor 24.0625, -74.4795.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-24",
    "title": "Vasco Da Gama's Arrival In Calicut",
    "year": 1498,
    "lat": 11.2588,
    "lng": 75.7877,
    "imageUrl": "/panoramas/1498_11.2588_75.7877_vasco-da-gama-s-arrival-in-calicut.jpg",
    "is360": true,
    "description": "Vasco Da Gama's Arrival In Calicut — panoramă istorică de 360°, surprinsă în anul 1498, în apropierea coordonatelor 11.2588, 75.7877.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 15-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-25",
    "title": "Unveiling Of The Sistine Chapel Ceiling",
    "year": 1512,
    "lat": 41.9029,
    "lng": 12.4534,
    "imageUrl": "/panoramas/1512_41.9029_12.4534_unveiling-of-the-sistine-chapel-ceiling.jpg",
    "is360": true,
    "description": "Unveiling Of The Sistine Chapel Ceiling — panoramă istorică de 360°, surprinsă în anul 1512, în apropierea coordonatelor 41.9029, 12.4534.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-26",
    "title": "Martin Luther Posts 95 Theses",
    "year": 1517,
    "lat": 51.866,
    "lng": 12.645,
    "imageUrl": "/panoramas/1517_51.8660_12.6450_martin-luther-posts-95-theses.jpg",
    "is360": true,
    "description": "Martin Luther Posts 95 Theses — panoramă istorică de 360°, surprinsă în anul 1517, în apropierea coordonatelor 51.8660, 12.6450.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-27",
    "title": "Magellan's Expedition Departs",
    "year": 1519,
    "lat": 37.3857,
    "lng": -5.9961,
    "imageUrl": "/panoramas/1519_37.3857_-5.9961_magellan-s-expedition-departs.jpg",
    "is360": true,
    "description": "Magellan's Expedition Departs — panoramă istorică de 360°, surprinsă în anul 1519, în apropierea coordonatelor 37.3857, -5.9961.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-28",
    "title": "Magellan's Death",
    "year": 1521,
    "lat": 10.301,
    "lng": 123.998,
    "imageUrl": "/panoramas/1521_10.3010_123.9980_magellan-s-death.jpg",
    "is360": true,
    "description": "Magellan's Death — panoramă istorică de 360°, surprinsă în anul 1521, în apropierea coordonatelor 10.3010, 123.9980.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-29",
    "title": "Pizarro's Capture Of Atahualpa",
    "year": 1532,
    "lat": -7.1557,
    "lng": -78.5137,
    "imageUrl": "/panoramas/1532_-7.1557_-78.5137_pizarro-s-capture-of-atahualpa.jpg",
    "is360": true,
    "description": "Pizarro's Capture Of Atahualpa — panoramă istorică de 360°, surprinsă în anul 1532, în apropierea coordonatelor -7.1557, -78.5137.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera sudică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-30",
    "title": "Copernicus Publishes De Revolutionibus Orbium Coelestium",
    "year": 1543,
    "lat": 54.3547,
    "lng": 19.6847,
    "imageUrl": "/panoramas/1543_54.3547_19.6847_copernicus-publishes-de-revolutionibus-orbium-coelestium.jpg",
    "is360": true,
    "description": "Copernicus Publishes De Revolutionibus Orbium Coelestium — panoramă istorică de 360°, surprinsă în anul 1543, în apropierea coordonatelor 54.3547, 19.6847.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-31",
    "title": "Battle Of Lepanto",
    "year": 1571,
    "lat": 38.3,
    "lng": 21.2833,
    "imageUrl": "/panoramas/1571_38.3000_21.2833_battle-of-lepanto.jpg",
    "is360": true,
    "description": "Battle Of Lepanto — panoramă istorică de 360°, surprinsă în anul 1571, în apropierea coordonatelor 38.3000, 21.2833.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-32",
    "title": "Defeat Of The Spanish Armada",
    "year": 1588,
    "lat": 50.3629,
    "lng": -4.1352,
    "imageUrl": "/panoramas/1588_50.3629_-4.1352_defeat-of-the-spanish-armada.jpg",
    "is360": true,
    "description": "Defeat Of The Spanish Armada — panoramă istorică de 360°, surprinsă în anul 1588, în apropierea coordonatelor 50.3629, -4.1352.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 16-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-33",
    "title": "Founding Of Jamestown",
    "year": 1607,
    "lat": 37.2285,
    "lng": -76.7825,
    "imageUrl": "/panoramas/1607_37.2285_-76.7825_founding-of-jamestown.jpg",
    "is360": true,
    "description": "Founding Of Jamestown — panoramă istorică de 360°, surprinsă în anul 1607, în apropierea coordonatelor 37.2285, -76.7825.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-34",
    "title": "Shah Jahan Lays Foundation Stone Of Taj Mahal",
    "year": 1631,
    "lat": 27.175,
    "lng": 78.0416,
    "imageUrl": "/panoramas/1631_27.1750_78.0416_shah-jahan-lays-foundation-stone-of-taj-mahal.jpg",
    "is360": true,
    "description": "Shah Jahan Lays Foundation Stone Of Taj Mahal — panoramă istorică de 360°, surprinsă în anul 1631, în apropierea coordonatelor 27.1750, 78.0416.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-35",
    "title": "Galileo's Trial For Heresy",
    "year": 1633,
    "lat": 41.8986,
    "lng": 12.477,
    "imageUrl": "/panoramas/1633_41.8986_12.4770_galileo-s-trial-for-heresy.jpg",
    "is360": true,
    "description": "Galileo's Trial For Heresy — panoramă istorică de 360°, surprinsă în anul 1633, în apropierea coordonatelor 41.8986, 12.4770.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-36",
    "title": "Signing Of The Treaty Of Westphalia",
    "year": 1648,
    "lat": 52.2785,
    "lng": 8.0483,
    "imageUrl": "/panoramas/1648_52.2785_8.0483_signing-of-the-treaty-of-westphalia.jpg",
    "is360": true,
    "description": "Signing Of The Treaty Of Westphalia — panoramă istorică de 360°, surprinsă în anul 1648, în apropierea coordonatelor 52.2785, 8.0483.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-37",
    "title": "Execution Of Charles I",
    "year": 1649,
    "lat": 51.5034,
    "lng": -0.1264,
    "imageUrl": "/panoramas/1649_51.5034_-0.1264_execution-of-charles-i.jpg",
    "is360": true,
    "description": "Execution Of Charles I — panoramă istorică de 360°, surprinsă în anul 1649, în apropierea coordonatelor 51.5034, -0.1264.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-38",
    "title": "Glorious Revolution",
    "year": 1688,
    "lat": 51.5036,
    "lng": -0.1265,
    "imageUrl": "/panoramas/1688_51.5036_-0.1265_glorious-revolution.jpg",
    "is360": true,
    "description": "Glorious Revolution — panoramă istorică de 360°, surprinsă în anul 1688, în apropierea coordonatelor 51.5036, -0.1265.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-39",
    "title": "Salem Witch Trials Begin",
    "year": 1692,
    "lat": 42.5444,
    "lng": -71.0189,
    "imageUrl": "/panoramas/1692_42.5444_-71.0189_salem-witch-trials-begin.jpg",
    "is360": true,
    "description": "Salem Witch Trials Begin — panoramă istorică de 360°, surprinsă în anul 1692, în apropierea coordonatelor 42.5444, -71.0189.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 17-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-40",
    "title": "Peter The Great Founds St Petersburg",
    "year": 1703,
    "lat": 59.9497,
    "lng": 30.3168,
    "imageUrl": "/panoramas/1703_59.9497_30.3168_peter-the-great-founds-st-petersburg.jpg",
    "is360": true,
    "description": "Peter The Great Founds St Petersburg — panoramă istorică de 360°, surprinsă în anul 1703, în apropierea coordonatelor 59.9497, 30.3168.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-41",
    "title": "Battle Of Poltava",
    "year": 1709,
    "lat": 49.6425,
    "lng": 34.4988,
    "imageUrl": "/panoramas/1709_49.6425_34.4988_battle-of-poltava.jpg",
    "is360": true,
    "description": "Battle Of Poltava — panoramă istorică de 360°, surprinsă în anul 1709, în apropierea coordonatelor 49.6425, 34.4988.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-42",
    "title": "Lisbon Earthquake",
    "year": 1755,
    "lat": 38.7077,
    "lng": -9.136,
    "imageUrl": "/panoramas/1755_38.7077_-9.1360_lisbon-earthquake.jpg",
    "is360": true,
    "description": "Lisbon Earthquake — panoramă istorică de 360°, surprinsă în anul 1755, în apropierea coordonatelor 38.7077, -9.1360.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-43",
    "title": "Landing Of Captain Cook",
    "year": 1770,
    "lat": -34.004,
    "lng": 151.183,
    "imageUrl": "/panoramas/1770_-34.0040_151.1830_landing-of-captain-cook.jpg",
    "is360": true,
    "description": "Landing Of Captain Cook — panoramă istorică de 360°, surprinsă în anul 1770, în apropierea coordonatelor -34.0040, 151.1830.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera sudică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-44",
    "title": "Boston Tea Party",
    "year": 1773,
    "lat": 42.3533,
    "lng": -71.0506,
    "imageUrl": "/panoramas/1773_42.3533_-71.0506_boston-tea-party.jpg",
    "is360": true,
    "description": "Boston Tea Party — panoramă istorică de 360°, surprinsă în anul 1773, în apropierea coordonatelor 42.3533, -71.0506.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-45",
    "title": "Signing Of The Declaration Of Independence",
    "year": 1776,
    "lat": 39.9488,
    "lng": -75.1498,
    "imageUrl": "/panoramas/1776_39.9488_-75.1498_signing-of-the-declaration-of-independence.jpg",
    "is360": true,
    "description": "Signing Of The Declaration Of Independence — panoramă istorică de 360°, surprinsă în anul 1776, în apropierea coordonatelor 39.9488, -75.1498.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-46",
    "title": "Signing Of The Declaration Of Independence",
    "year": 1776,
    "lat": 39.9489,
    "lng": -75.15,
    "imageUrl": "/panoramas/1776_39.9489_-75.1500_signing-of-the-declaration-of-independence.jpg",
    "is360": true,
    "description": "Signing Of The Declaration Of Independence — panoramă istorică de 360°, surprinsă în anul 1776, în apropierea coordonatelor 39.9489, -75.1500.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-47",
    "title": "First Fleet Arrival",
    "year": 1788,
    "lat": -33.8587,
    "lng": 151.2104,
    "imageUrl": "/panoramas/1788_-33.8587_151.2104_first-fleet-arrival.jpg",
    "is360": true,
    "description": "First Fleet Arrival — panoramă istorică de 360°, surprinsă în anul 1788, în apropierea coordonatelor -33.8587, 151.2104.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera sudică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-48",
    "title": "Declaration Of The Rights Of Man And Of The Citizen",
    "year": 1789,
    "lat": 48.7997,
    "lng": 2.1261,
    "imageUrl": "/panoramas/1789_48.7997_2.1261_declaration-of-the-rights-of-man-and-of-the-citizen.jpg",
    "is360": true,
    "description": "Declaration Of The Rights Of Man And Of The Citizen — panoramă istorică de 360°, surprinsă în anul 1789, în apropierea coordonatelor 48.7997, 2.1261.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-49",
    "title": "Execution Of Louis Xvi",
    "year": 1793,
    "lat": 48.8655,
    "lng": 2.3218,
    "imageUrl": "/panoramas/1793_48.8655_2.3218_execution-of-louis-xvi.jpg",
    "is360": true,
    "description": "Execution Of Louis Xvi — panoramă istorică de 360°, surprinsă în anul 1793, în apropierea coordonatelor 48.8655, 2.3218.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 18-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-50",
    "title": "Signing Of The Treaty Of Ghent",
    "year": 1814,
    "lat": 51.0543,
    "lng": 3.7226,
    "imageUrl": "/panoramas/1814_51.0543_3.7226_signing-of-the-treaty-of-ghent.jpg",
    "is360": true,
    "description": "Signing Of The Treaty Of Ghent — panoramă istorică de 360°, surprinsă în anul 1814, în apropierea coordonatelor 51.0543, 3.7226.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-51",
    "title": "Battle Of Waterloo",
    "year": 1815,
    "lat": 50.6789,
    "lng": 4.4072,
    "imageUrl": "/panoramas/1815_50.6789_4.4072_battle-of-waterloo.jpg",
    "is360": true,
    "description": "Battle Of Waterloo — panoramă istorică de 360°, surprinsă în anul 1815, în apropierea coordonatelor 50.6789, 4.4072.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-52",
    "title": "First Passenger Railway Journey",
    "year": 1825,
    "lat": 54.6053,
    "lng": -1.6378,
    "imageUrl": "/panoramas/1825_54.6053_-1.6378_first-passenger-railway-journey.jpg",
    "is360": true,
    "description": "First Passenger Railway Journey — panoramă istorică de 360°, surprinsă în anul 1825, în apropierea coordonatelor 54.6053, -1.6378.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-53",
    "title": "Gettysburg Address",
    "year": 1863,
    "lat": 39.8143,
    "lng": -77.2325,
    "imageUrl": "/panoramas/1863_39.8143_-77.2325_gettysburg-address.jpg",
    "is360": true,
    "description": "Gettysburg Address — panoramă istorică de 360°, surprinsă în anul 1863, în apropierea coordonatelor 39.8143, -77.2325.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-54",
    "title": "Assassination Of Abraham Lincoln",
    "year": 1865,
    "lat": 38.8978,
    "lng": -77.0267,
    "imageUrl": "/panoramas/1865_38.8978_-77.0267_assassination-of-abraham-lincoln.jpg",
    "is360": true,
    "description": "Assassination Of Abraham Lincoln — panoramă istorică de 360°, surprinsă în anul 1865, în apropierea coordonatelor 38.8978, -77.0267.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-55",
    "title": "Opening Of The Suez Canal",
    "year": 1869,
    "lat": 31.2642,
    "lng": 32.2902,
    "imageUrl": "/panoramas/1869_31.2642_32.2902_opening-of-the-suez-canal.jpg",
    "is360": true,
    "description": "Opening Of The Suez Canal — panoramă istorică de 360°, surprinsă în anul 1869, în apropierea coordonatelor 31.2642, 32.2902.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-56",
    "title": "Opening Of The Brooklyn Bridge",
    "year": 1883,
    "lat": 40.7052,
    "lng": -73.9967,
    "imageUrl": "/panoramas/1883_40.7052_-73.9967_opening-of-the-brooklyn-bridge.jpg",
    "is360": true,
    "description": "Opening Of The Brooklyn Bridge — panoramă istorică de 360°, surprinsă în anul 1883, în apropierea coordonatelor 40.7052, -73.9967.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-57",
    "title": "Battle Of Adwa",
    "year": 1896,
    "lat": 14.167,
    "lng": 38.9,
    "imageUrl": "/panoramas/1896_14.1670_38.9000_battle-of-adwa.jpg",
    "is360": true,
    "description": "Battle Of Adwa — panoramă istorică de 360°, surprinsă în anul 1896, în apropierea coordonatelor 14.1670, 38.9000.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-58",
    "title": "First Modern Olympic Games",
    "year": 1896,
    "lat": 37.95,
    "lng": 23.7333,
    "imageUrl": "/panoramas/1896_37.9500_23.7333_first-modern-olympic-games.jpg",
    "is360": true,
    "description": "First Modern Olympic Games — panoramă istorică de 360°, surprinsă în anul 1896, în apropierea coordonatelor 37.9500, 23.7333.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-59",
    "title": "Assassination Of Empress Elisabeth",
    "year": 1898,
    "lat": 46.2081,
    "lng": 6.1554,
    "imageUrl": "/panoramas/1898_46.2081_6.1554_assassination-of-empress-elisabeth.jpg",
    "is360": true,
    "description": "Assassination Of Empress Elisabeth — panoramă istorică de 360°, surprinsă în anul 1898, în apropierea coordonatelor 46.2081, 6.1554.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 19-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-60",
    "title": "First Flight Of The Wright Brothers",
    "year": 1903,
    "lat": 36.027,
    "lng": -75.68,
    "imageUrl": "/panoramas/1903_36.0270_-75.6800_first-flight-of-the-wright-brothers.jpg",
    "is360": true,
    "description": "First Flight Of The Wright Brothers — panoramă istorică de 360°, surprinsă în anul 1903, în apropierea coordonatelor 36.0270, -75.6800.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-61",
    "title": "Assassination Of Archduke Franz Ferdinand",
    "year": 1914,
    "lat": 43.8584,
    "lng": 18.4286,
    "imageUrl": "/panoramas/1914_43.8584_18.4286_assassination-of-archduke-franz-ferdinand.jpg",
    "is360": true,
    "description": "Assassination Of Archduke Franz Ferdinand — panoramă istorică de 360°, surprinsă în anul 1914, în apropierea coordonatelor 43.8584, 18.4286.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-62",
    "title": "Signing Of The Treaty Of Versailles",
    "year": 1919,
    "lat": 48.804,
    "lng": 2.1204,
    "imageUrl": "/panoramas/1919_48.8040_2.1204_signing-of-the-treaty-of-versailles.jpg",
    "is360": true,
    "description": "Signing Of The Treaty Of Versailles — panoramă istorică de 360°, surprinsă în anul 1919, în apropierea coordonatelor 48.8040, 2.1204.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-63",
    "title": "Discovery Of Tutankhamun's Tomb",
    "year": 1922,
    "lat": 25.74,
    "lng": 32.601,
    "imageUrl": "/panoramas/1922_25.7400_32.6010_discovery-of-tutankhamun-s-tomb.jpg",
    "is360": true,
    "description": "Discovery Of Tutankhamun's Tomb — panoramă istorică de 360°, surprinsă în anul 1922, în apropierea coordonatelor 25.7400, 32.6010.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-64",
    "title": "Stock Market Crash Black Tuesday",
    "year": 1929,
    "lat": 40.7067,
    "lng": -74.0113,
    "imageUrl": "/panoramas/1929_40.7067_-74.0113_stock-market-crash-black-tuesday.jpg",
    "is360": true,
    "description": "Stock Market Crash Black Tuesday — panoramă istorică de 360°, surprinsă în anul 1929, în apropierea coordonatelor 40.7067, -74.0113.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-65",
    "title": "Mahatma Gandhi's Salt March",
    "year": 1930,
    "lat": 20.8406,
    "lng": 72.8257,
    "imageUrl": "/panoramas/1930_20.8406_72.8257_mahatma-gandhi-s-salt-march.jpg",
    "is360": true,
    "description": "Mahatma Gandhi's Salt March — panoramă istorică de 360°, surprinsă în anul 1930, în apropierea coordonatelor 20.8406, 72.8257.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-66",
    "title": "Pearl Harbor Attack",
    "year": 1941,
    "lat": 21.3653,
    "lng": -157.9497,
    "imageUrl": "/panoramas/1941_21.3653_-157.9497_pearl-harbor-attack.jpg",
    "is360": true,
    "description": "Pearl Harbor Attack — panoramă istorică de 360°, surprinsă în anul 1941, în apropierea coordonatelor 21.3653, -157.9497.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică vestul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-67",
    "title": "Battle Of Stalingrad",
    "year": 1943,
    "lat": 48.7422,
    "lng": 44.5372,
    "imageUrl": "/panoramas/1943_48.7422_44.5372_battle-of-stalingrad.jpg",
    "is360": true,
    "description": "Battle Of Stalingrad — panoramă istorică de 360°, surprinsă în anul 1943, în apropierea coordonatelor 48.7422, 44.5372.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-68",
    "title": "Declaration Of Indian Independence",
    "year": 1947,
    "lat": 28.6562,
    "lng": 77.241,
    "imageUrl": "/panoramas/1947_28.6562_77.2410_declaration-of-indian-independence.jpg",
    "is360": true,
    "description": "Declaration Of Indian Independence — panoramă istorică de 360°, surprinsă în anul 1947, în apropierea coordonatelor 28.6562, 77.2410.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-69",
    "title": "Assassination Of Mohandas Gandhi",
    "year": 1948,
    "lat": 28.6133,
    "lng": 77.2064,
    "imageUrl": "/panoramas/1948_28.6133_77.2064_assassination-of-mohandas-gandhi.jpg",
    "is360": true,
    "description": "Assassination Of Mohandas Gandhi — panoramă istorică de 360°, surprinsă în anul 1948, în apropierea coordonatelor 28.6133, 77.2064.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-70",
    "title": "Tiananmen Square Protests",
    "year": 1989,
    "lat": 39.9042,
    "lng": 116.3917,
    "imageUrl": "/panoramas/1989_39.9042_116.3917_tiananmen-square-protests.jpg",
    "is360": true,
    "description": "Tiananmen Square Protests — panoramă istorică de 360°, surprinsă în anul 1989, în apropierea coordonatelor 39.9042, 116.3917.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 20-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-71",
    "title": "Crucifixion Of Jesus Christ",
    "year": 33,
    "lat": 31.782,
    "lng": 35.228,
    "imageUrl": "/panoramas/33_31.7820_35.2280_crucifixion-of-jesus-christ.jpg",
    "is360": true,
    "description": "Crucifixion Of Jesus Christ — panoramă istorică de 360°, surprinsă în anul 33, în apropierea coordonatelor 31.7820, 35.2280.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-72",
    "title": "Fall Of The Western Roman Empire",
    "year": 476,
    "lat": 44.4206,
    "lng": 12.1963,
    "imageUrl": "/panoramas/476_44.4206_12.1963_fall-of-the-western-roman-empire.jpg",
    "is360": true,
    "description": "Fall Of The Western Roman Empire — panoramă istorică de 360°, surprinsă în anul 476, în apropierea coordonatelor 44.4206, 12.1963.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 5-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-73",
    "title": "Hagia Sophia Consecration",
    "year": 537,
    "lat": 41.0086,
    "lng": 28.9801,
    "imageUrl": "/panoramas/537_41.0086_28.9801_hagia-sophia-consecration.jpg",
    "is360": true,
    "description": "Hagia Sophia Consecration — panoramă istorică de 360°, surprinsă în anul 537, în apropierea coordonatelor 41.0086, 28.9801.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 6-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-74",
    "title": "Battle Of Tours",
    "year": 732,
    "lat": 46.7766,
    "lng": 0.4072,
    "imageUrl": "/panoramas/732_46.7766_0.4072_battle-of-tours.jpg",
    "is360": true,
    "description": "Battle Of Tours — panoramă istorică de 360°, surprinsă în anul 732, în apropierea coordonatelor 46.7766, 0.4072.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 8-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-75",
    "title": "Founding Of Baghdad",
    "year": 762,
    "lat": 33.3364,
    "lng": 44.3626,
    "imageUrl": "/panoramas/762_33.3364_44.3626_founding-of-baghdad.jpg",
    "is360": true,
    "description": "Founding Of Baghdad — panoramă istorică de 360°, surprinsă în anul 762, în apropierea coordonatelor 33.3364, 44.3626.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 8-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-76",
    "title": "Eruption Of Mount Vesuvius",
    "year": 79,
    "lat": 40.7517,
    "lng": 14.4983,
    "imageUrl": "/panoramas/79_40.7517_14.4983_eruption-of-mount-vesuvius.jpg",
    "is360": true,
    "description": "Eruption Of Mount Vesuvius — panoramă istorică de 360°, surprinsă în anul 79, în apropierea coordonatelor 40.7517, 14.4983.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 1-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  },
  {
    "id": "pano-77",
    "title": "Coronation Of Charlemagne",
    "year": 800,
    "lat": 41.9022,
    "lng": 12.4533,
    "imageUrl": "/panoramas/800_41.9022_12.4533_coronation-of-charlemagne.jpg",
    "is360": true,
    "description": "Coronation Of Charlemagne — panoramă istorică de 360°, surprinsă în anul 800, în apropierea coordonatelor 41.9022, 12.4533.",
    "clues": [
      "Evenimentul s-a petrecut în secolul al 8-lea d.Hr.",
      "Locul se află în emisfera nordică.",
      "Coordonatele indică estul meridianului Greenwich."
    ]
  }
];

// Temporal span of the panorama pool, used to scale the timeline slider.
export const PANORAMA_MIN_YEAR = -2560;
export const PANORAMA_MAX_YEAR = 1989;
